Applied shfmt

diff --git a/de b/de
--- a/de
+++ b/de
@@ -38,7 +38,7 @@ declare -r FUZZY_SEARCH_WHEN_BLANK=true
 # --------------------- #
 
 function usage() {
-	cat <<EOF
+  cat <<EOF
 Adds directory stacking, ls after cd, and fuzzy finding behavior to cd.
 
 Usage: $(basename "$0") [-L/-P [-e]] [-h] [-v] [-l] [-s[=][DIRECTORY]/-p[=][0-9]+] [PATH]
@@ -57,7 +57,7 @@ EOF
 }
 
 function version() {
-	cat <<EOF
+  cat <<EOF
 Directory Explorer 0.1.0
 Copyright © 2026 Josh Beale <jbeale2023@gmail.com>.
 Licence MIT: <https://directory.fsf.org/wiki/License:Expat>
@@ -69,82 +69,82 @@ EOF
 # If there are directories on the stack, list them, one per line, with added line numbers.
 # If there are more than $STACK_DISPLAY_LIMIT directories in the stack, truncate the output.
 function list-directories() {
-	if [ -f "${USER_DIRSTACK:-$HOME/.dirstack}" ]; then
-		declare -i STACK_SIZE
-		STACK_SIZE=$(wc -l "${USER_DIRSTACK:-$HOME/.dirstack}" | cut -f 1 -d " ")
-		[ "$STACK_SIZE" -ge 1 ] || { echo "The directory stack is empty." && return 0; }
-		echo "There are currently $STACK_SIZE directories on the stack."
-		tac "${USER_DIRSTACK:-$HOME/.dirstack}" | head -n "${STACK_DISPLAY_LIMIT:-5}" | cat -n
-	else
-		echo "The directory stack is empty." && return 0
-	fi
+  if [ -f "${USER_DIRSTACK:-$HOME/.dirstack}" ]; then
+    declare -i STACK_SIZE
+    STACK_SIZE=$(wc -l "${USER_DIRSTACK:-$HOME/.dirstack}" | cut -f 1 -d " ")
+    [ "$STACK_SIZE" -ge 1 ] || { echo "The directory stack is empty." && return 0; }
+    echo "There are currently $STACK_SIZE directories on the stack."
+    tac "${USER_DIRSTACK:-$HOME/.dirstack}" | head -n "${STACK_DISPLAY_LIMIT:-5}" | cat -n
+  else
+    echo "The directory stack is empty." && return 0
+  fi
 }
 
 # Add a directory to the stack.
 # Defaults to $PWD if no directory is provided.
 function stack-directory() {
-	if [ "$#" -eq 0 ]; then
-		realpath "$PWD" >>"${USER_DIRSTACK:-$HOME/.dirstack}"
-	else
-		realpath "$1" >>"${USER_DIRSTACK:-$HOME/.dirstack}"
-	fi
-	declare -i STACK_SIZE
-	STACK_SIZE=$(wc -l "${USER_DIRSTACK:-$HOME/.dirstack}" | cut -f 1 -d " ")
-	(("STACK_SIZE" == 1)) && { echo "There is currently 1 directory on the stack." && return 0; }
-	echo "There are currently $STACK_SIZE directories on the stack." && return 0
+  if [ "$#" -eq 0 ]; then
+    realpath "$PWD" >>"${USER_DIRSTACK:-$HOME/.dirstack}"
+  else
+    realpath "$1" >>"${USER_DIRSTACK:-$HOME/.dirstack}"
+  fi
+  declare -i STACK_SIZE
+  STACK_SIZE=$(wc -l "${USER_DIRSTACK:-$HOME/.dirstack}" | cut -f 1 -d " ")
+  (("STACK_SIZE" == 1)) && { echo "There is currently 1 directory on the stack." && return 0; }
+  echo "There are currently $STACK_SIZE directories on the stack." && return 0
 }
 
 # If there is a directory on top of the stack, pop it and change to it.
 # Optionally, instead select the directory specified by user numerical input.
 function pop-directory() {
-	if [ -f "${USER_DIRSTACK:-$HOME/.dirstack}" ]; then
-		declare -i STACK_SIZE
-		STACK_SIZE=$(wc -l "${USER_DIRSTACK:-$HOME/.dirstack}" | cut -f 1 -d " ")
-		[ "$STACK_SIZE" -ge 1 ] || { echo "The directory stack is empty." && return 1; }
-		local STACK_TOP
-		if [ "$#" -eq 0 ]; then
-			STACK_TOP=$(tail -n 1 "${USER_DIRSTACK:-$HOME/.dirstack}" | tee >(wc -c | xargs -I {} truncate "${USER_DIRSTACK:-$HOME/.dirstack}" -s -{})) &&
-				builtin cd "${cdopts[@]}" "$STACK_TOP" &&
-				echo "Popped $STACK_TOP from the stack." && {
-				if (("$STACK_SIZE" >= 3)); then
-					echo "There are currently $((--STACK_SIZE)) directories on the stack."
-				elif [[ "$STACK_SIZE" == 2 ]]; then
-					echo "There is currently $((--STACK_SIZE)) directory on the stack."
-				else
-					echo "The directory stack is empty."
-				fi
-				[ "$LS_AFTER_CD" ] && ls
-			} || return 1
-		else
-			[[ $1 =~ [0-9]+ ]] && declare -ir DIRNUM="$1"
-			{ [[ ! $1 =~ [0-9]+ ]] || [[ "$DIRNUM" > "$STACK_SIZE" ]]; } && { echo "Invalid stack index $1" && return 1; }
-			STACK_TOP=$(sed -i -e "$DIRNUM w /dev/stdout" -e "$DIRNUM d" "${USER_DIRSTACK:-$HOME/.dirstack}")
-			builtin cd "${cdopts[@]}" "$STACK_TOP" &&
-				echo "Popped $STACK_TOP from the stack." && {
-				if (("$STACK_SIZE" >= 3)); then
-					echo "There are currently $((--STACK_SIZE)) directories on the stack."
-				elif [[ "$STACK_SIZE" == 2 ]]; then
-					echo "There is currently $((--STACK_SIZE)) directory on the stack."
-				else
-					echo "The directory stack is empty."
-				fi
-				[ "$LS_AFTER_CD" ] && ls
-			} || return 1
-		fi
-	else
-		(echo "The directory stack is empty." && exit 1)
-	fi
+  if [ -f "${USER_DIRSTACK:-$HOME/.dirstack}" ]; then
+    declare -i STACK_SIZE
+    STACK_SIZE=$(wc -l "${USER_DIRSTACK:-$HOME/.dirstack}" | cut -f 1 -d " ")
+    [ "$STACK_SIZE" -ge 1 ] || { echo "The directory stack is empty." && return 1; }
+    local STACK_TOP
+    if [ "$#" -eq 0 ]; then
+      STACK_TOP=$(tail -n 1 "${USER_DIRSTACK:-$HOME/.dirstack}" | tee >(wc -c | xargs -I {} truncate "${USER_DIRSTACK:-$HOME/.dirstack}" -s -{})) &&
+        builtin cd "${cdopts[@]}" "$STACK_TOP" &&
+        echo "Popped $STACK_TOP from the stack." && {
+        if (("$STACK_SIZE" >= 3)); then
+          echo "There are currently $((--STACK_SIZE)) directories on the stack."
+        elif [[ "$STACK_SIZE" == 2 ]]; then
+          echo "There is currently $((--STACK_SIZE)) directory on the stack."
+        else
+          echo "The directory stack is empty."
+        fi
+        [ "$LS_AFTER_CD" ] && ls
+      } || return 1
+    else
+      [[ $1 =~ [0-9]+ ]] && declare -ir DIRNUM="$1"
+      { [[ ! $1 =~ [0-9]+ ]] || [[ "$DIRNUM" > "$STACK_SIZE" ]]; } && { echo "Invalid stack index $1" && return 1; }
+      STACK_TOP=$(sed -i -e "$DIRNUM w /dev/stdout" -e "$DIRNUM d" "${USER_DIRSTACK:-$HOME/.dirstack}")
+      builtin cd "${cdopts[@]}" "$STACK_TOP" &&
+        echo "Popped $STACK_TOP from the stack." && {
+        if (("$STACK_SIZE" >= 3)); then
+          echo "There are currently $((--STACK_SIZE)) directories on the stack."
+        elif [[ "$STACK_SIZE" == 2 ]]; then
+          echo "There is currently $((--STACK_SIZE)) directory on the stack."
+        else
+          echo "The directory stack is empty."
+        fi
+        [ "$LS_AFTER_CD" ] && ls
+      } || return 1
+    fi
+  else
+    (echo "The directory stack is empty." && exit 1)
+  fi
 }
 
 # If there are directories on the stack, empty it.
 function purge-directory-stack() {
-	if [ -f "${USER_DIRSTACK:-$HOME/.dirstack}" ]; then
-		declare -i STACK_SIZE
-		STACK_SIZE=$(wc -l "${USER_DIRSTACK:-$HOME/.dirstack}" | cut -f 1 -d " ")
-		[ "$STACK_SIZE" -ge 1 ] || { echo "The directory stack is empty." && return 0; }
-		echo "Purging $STACK_SIZE directories from the stack."
-		rm "${USER_DIRSTACK:-$HOME/.dirstack}"
-	fi
+  if [ -f "${USER_DIRSTACK:-$HOME/.dirstack}" ]; then
+    declare -i STACK_SIZE
+    STACK_SIZE=$(wc -l "${USER_DIRSTACK:-$HOME/.dirstack}" | cut -f 1 -d " ")
+    [ "$STACK_SIZE" -ge 1 ] || { echo "The directory stack is empty." && return 0; }
+    echo "Purging $STACK_SIZE directories from the stack."
+    rm "${USER_DIRSTACK:-$HOME/.dirstack}"
+  fi
 }
 
 # vim: set filetype=bash:
